# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: trivyops
before:
  hooks:
    - go mod tidy
builds:
  - id: container
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
  - id: cli
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - builds:
      - container
    replacements:
      linux: Linux
      amd64: x86_64
    name_template: "{{ .ProjectName }}_cgo_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - builds:
      - cli
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# .goreleaser.yaml
brews:
  -
    # GitHub/GitLab repository to push the formula to
    tap:
      owner: steffakasid
      name: homebrew-trivyops
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    commit_author:
      name: goreleaserbot
      email: goreleaser@steffen-rumpf.de


    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    homepage: "https://github.com/steffakasid/trivy-project-scanner"
    description: "This tool can be used to scan GitLab for trivy results"
    license: "Apache-2.0"
